#!/usr/bin/env bash

SCRIPT_DIR=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
BASE_DIR=$SCRIPT_DIR/..
cd $BASE_DIR

# install virtualenv if necessary
if hash virtualenv 2>/dev/null; then
  echo "virtualenv already installed, skipping"
else
  echo "Going to install virtualenv (using sudo - you may be prompted to enter password)"
  sudo pip install virtualenv
fi

#setup environment
virtualenv env
source env/bin/activate


# need archflags because XCode had some changes between 4.X to 5.X that causes the installation of numpy to fail
# need --allow-all-external because cdecimal fails to install (hosted externally from PyPi is why I believe)
ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future pip install --allow-all-external -r requirements.txt
